"""add invitation children

Revision ID: d620651f11a1
Revises: 8b06229b4124
Create Date: 2026-08-15 21:33:14.636936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd620651f11a1'
down_revision: Union[str, None] = '8b06229b4124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_children',
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_id', 'child_id', name='uq_invitation_children')
    )
    op.create_index(op.f('ix_invitation_children_child_id'), 'invitation_children', ['child_id'], unique=False)
    op.create_index(op.f('ix_invitation_children_invitation_id'), 'invitation_children', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_invitation_children_organization_id'), 'invitation_children', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_children_organization_id'), table_name='invitation_children')
    op.drop_index(op.f('ix_invitation_children_invitation_id'), table_name='invitation_children')
    op.drop_index(op.f('ix_invitation_children_child_id'), table_name='invitation_children')
    op.drop_table('invitation_children')
    # ### end Alembic commands ###
